services:
  - type: web
    name: teamsync-client
    env: static
    staticPublishPath: dist
    buildCommand: npm run build
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
